// Generated by gencpp from file motor_ctrl_20/motor_rece.msg
// DO NOT EDIT!


#ifndef MOTOR_CTRL_20_MESSAGE_MOTOR_RECE_H
#define MOTOR_CTRL_20_MESSAGE_MOTOR_RECE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_ctrl_20
{
template <class ContainerAllocator>
struct motor_rece_
{
  typedef motor_rece_<ContainerAllocator> Type;

  motor_rece_()
    : motor1pos(0.0)
    , motor2pos(0.0)  {
    }
  motor_rece_(const ContainerAllocator& _alloc)
    : motor1pos(0.0)
    , motor2pos(0.0)  {
  (void)_alloc;
    }



   typedef double _motor1pos_type;
  _motor1pos_type motor1pos;

   typedef double _motor2pos_type;
  _motor2pos_type motor2pos;





  typedef boost::shared_ptr< ::motor_ctrl_20::motor_rece_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_ctrl_20::motor_rece_<ContainerAllocator> const> ConstPtr;

}; // struct motor_rece_

typedef ::motor_ctrl_20::motor_rece_<std::allocator<void> > motor_rece;

typedef boost::shared_ptr< ::motor_ctrl_20::motor_rece > motor_recePtr;
typedef boost::shared_ptr< ::motor_ctrl_20::motor_rece const> motor_receConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_ctrl_20::motor_rece_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_ctrl_20::motor_rece_<ContainerAllocator1> & lhs, const ::motor_ctrl_20::motor_rece_<ContainerAllocator2> & rhs)
{
  return lhs.motor1pos == rhs.motor1pos &&
    lhs.motor2pos == rhs.motor2pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_ctrl_20::motor_rece_<ContainerAllocator1> & lhs, const ::motor_ctrl_20::motor_rece_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_ctrl_20

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_ctrl_20::motor_rece_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_ctrl_20::motor_rece_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_ctrl_20::motor_rece_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b93a1d04bd7942fecb98ba3b116d262";
  }

  static const char* value(const ::motor_ctrl_20::motor_rece_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b93a1d04bd7942fULL;
  static const uint64_t static_value2 = 0xecb98ba3b116d262ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_ctrl_20/motor_rece";
  }

  static const char* value(const ::motor_ctrl_20::motor_rece_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 motor1pos\n"
"float64 motor2pos\n"
;
  }

  static const char* value(const ::motor_ctrl_20::motor_rece_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1pos);
      stream.next(m.motor2pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_rece_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_ctrl_20::motor_rece_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_ctrl_20::motor_rece_<ContainerAllocator>& v)
  {
    s << indent << "motor1pos: ";
    Printer<double>::stream(s, indent + "  ", v.motor1pos);
    s << indent << "motor2pos: ";
    Printer<double>::stream(s, indent + "  ", v.motor2pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CTRL_20_MESSAGE_MOTOR_RECE_H
